[package]
name = "emu65x64"
version = "0.1.0"
edition = "2021"

[features]
# default = ["bevy"]
bevy = ["dep:bevy"]

[dependencies]
# libc = "0.2.159"
bevy = { version = "0.14.2", optional = true, default-features = false }

[build-dependencies]
cc = "1.1.28"
